# -------- Build stage --------
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build -- --configuration production

# -------- Production stage --------
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

# Correct Angular output folder
COPY --from=build /app/dist/angular-15-crud/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
